### ISSUE TITLE
“The Operation was rejected by your operating system”

### ISSUE THREAD

**Issue by shubhankartrivedi** [thebaselab/react-starter#1]
I’m getting t his error when I try to do “npm run start” as mentioned after doing “npm i” in the readme file.
I’m using the latest Code App on iPad Air 5th Gen 64 GB .

**Comment by shubhankartrivedi** [comment]
Tbh, I'm getting the same error on installing/running anything npm related.

**Comment by bummoblizard** [comment]
Hi. Can you share a screenshot with the full error message? You might also try to restart your device.

**Comment by shubhankartrivedi** [comment]
I could have gave but now I have refunded the app.

**Comment by bummoblizard** [comment]
Sorry to hear that. If you wish to give it another try, here's the TestFlight link: https://testflight.apple.com/join/EgZ8sE2P

**Comment by shubhankartrivedi** [comment]
Sure! I will try it out and let you know if any errors.
Will buy it if it works perfect.

**Comment by Taikylah** [comment]
Hi, I do have the same issue

**Comment by shubhankartrivedi** [comment]
> Hi, I do have the same issue

Don't know what to do now

**Comment by Taikylah** [comment]
Oh well too late for me to refund the app so I guess I gave him a coffee 😅
